version: "3.8"
services:
    api:
        container_name: api_backend
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin_ui
        ports:
          - "5050:80"
        depends_on:
          - db 
        environment:
          PGADMIN_DEFAULT_EMAIL: omaressamhegazy6@gmail.com
          PGADMIN_DEFAULT_PASSWORD: password 
volumes:
    db: ~
